version: '3.8'

services:
  gtstore:
    build:
      context: .
      dockerfile: Dockerfile
    image: gtstore-dev
    container_name: gtstore
    volumes:
      - .:/app
      - build_cache:/app/build
    working_dir: /app
    command: bash
    stdin_open: true
    tty: true
    ports:
      - "50051-50053:50051-50053"  # Port range for gRPC services

volumes:
  build_cache:
